## numpy & pandas 

In [1]:
import numpy as np

In [2]:
list1 = [1,2,3,4,5,6,7,8,9]
array1 = np.array(list1)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [3]:
array2D = np.array([[1,2,3],[4,5,6]])
print(array2D)

[[1 2 3]
 [4 5 6]]


In [4]:
array3D = np.array([[[1,2,3],[4,5,6]], [[7,8,9],[10,11,12]]])
print(array3D)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [5]:
annualSalesAndImprovements = np.array([[10000,20000, 30000], [0,100,100]])

In [6]:
print(annualSalesAndImprovements)

[[10000 20000 30000]
 [    0   100   100]]


In [7]:
annualSalesAndImprovements.ndim

2

In [8]:
annualSalesAndImprovements.size

6

In [9]:
annualSalesAndImprovements.shape

(2, 3)

In [11]:
sales = np.zeros((5,3))
print(sales)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
sales[2] = 10
print(sales)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [10. 10. 10.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [13]:
print(sales[-1])

[0. 0. 0.]


In [14]:
sales2 = np.ones((5,))
print(sales2)

[1. 1. 1. 1. 1.]


In [15]:
np.arange(1,10,3)

array([1, 4, 7])

In [16]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.rand(4,4)

array([[0.37260983, 0.46898024, 0.5182869 , 0.7306253 ],
       [0.2995038 , 0.11514002, 0.53964149, 0.1703768 ],
       [0.70161664, 0.14928045, 0.25826156, 0.25201231],
       [0.74210427, 0.43363529, 0.43855392, 0.49264356]])

In [18]:
np.random.randint(1,100,(4,4))

array([[50, 58, 13, 17],
       [56, 17, 93, 52],
       [31, 25, 97, 91],
       [51, 87, 35, 68]])

In [19]:
array10 = np.array([10,20,30,40,50,60,70,80,90,100])
print(array10[2:5])

[30 40 50]


In [20]:
print(array10[:5])

[10 20 30 40 50]


In [21]:
print(array10[2:])

[ 30  40  50  60  70  80  90 100]


In [23]:
print(array10[::2])

[10 30 50 70 90]


In [24]:
array11 = np.array([10,20,30,40,50,60,70,80,90,100])
array12 = np.array([100,200,300,400,500,600,700,800,900,1000])


In [25]:
print(array11 + array12)

[ 110  220  330  440  550  660  770  880  990 1100]


In [26]:
print(array11 - array12)

[ -90 -180 -270 -360 -450 -540 -630 -720 -810 -900]


In [27]:
print(array11 * array12)

[  1000   4000   9000  16000  25000  36000  49000  64000  81000 100000]


In [28]:
print(array11 / array12)

[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]


In [30]:
sqrtofArray11 = np.sqrt(array11)
print(sqrtofArray11)

[ 3.16227766  4.47213595  5.47722558  6.32455532  7.07106781  7.74596669
  8.36660027  8.94427191  9.48683298 10.        ]


### Homework
| Numpy'da aşağıdaki işlemleri nasıl yaparım. Ar-Ge

| Kural: Gerçek hayat verisi ve isimlendirme

- Matris Çarpımı
- Transpoz Nedir ? Nasıl yapılır ?
- Reshaping and flattening
- Concatination, hstach, vstack